app:
    db-init: true
server:
    port: 8443
    ssl:
        key-store: classpath:keys/mykeys.jks
        key-store-password: travelbase
        key-password: travelbase
spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:file:~/test;INIT=CREATE SCHEMA IF NOT EXISTS TRAVELBASE
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                default_schema: TRAVELBASE
